highlighter: pygments
exclude: [README.markdown]
permalink: /:title.html
paginate: 3
markdown: rdiscount
title: Pranjal's blog
author :
       name: Pranjal Yadav
       email: godricglow@gmail.com
       github: PranY
description: This is the official blog!
url: http://prany.github.io 
theme: jekyll-theme-cayman