lsi: false
pygments: true
exclude: README.markdown
permalink: /:title.html
markdown: maruku
title: Pranjal's blog
author :
       name: Pranjal Yadav
       email: godricglow@gmail.com
       github: PranY
description: This is the official blog!
url: http://prany.github.io 